// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdG0DmOihlLVuEEWUrwr_QytoVAFM9QIY',
    appId: '1:933559243147:web:e81a11381d40f863255f8e',
    messagingSenderId: '933559243147',
    projectId: 'a4c-shop-ae65c',
    authDomain: 'a4c-shop-ae65c.firebaseapp.com',
    storageBucket: 'a4c-shop-ae65c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAskEUeqkdNE-ba1ODwT1NT_um0VH0FFbg',
    appId: '1:933559243147:android:066ed2e5da3137b3255f8e',
    messagingSenderId: '933559243147',
    projectId: 'a4c-shop-ae65c',
    storageBucket: 'a4c-shop-ae65c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_I7AbfHZax0IwUqd5Fgqe-xDlGQ7c5bU',
    appId: '1:933559243147:ios:d2ed60ffa3261c39255f8e',
    messagingSenderId: '933559243147',
    projectId: 'a4c-shop-ae65c',
    storageBucket: 'a4c-shop-ae65c.appspot.com',
    iosBundleId: 'com.example.allforcShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_I7AbfHZax0IwUqd5Fgqe-xDlGQ7c5bU',
    appId: '1:933559243147:ios:d2ed60ffa3261c39255f8e',
    messagingSenderId: '933559243147',
    projectId: 'a4c-shop-ae65c',
    storageBucket: 'a4c-shop-ae65c.appspot.com',
    iosBundleId: 'com.example.allforcShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdG0DmOihlLVuEEWUrwr_QytoVAFM9QIY',
    appId: '1:933559243147:web:d49a3851082215df255f8e',
    messagingSenderId: '933559243147',
    projectId: 'a4c-shop-ae65c',
    authDomain: 'a4c-shop-ae65c.firebaseapp.com',
    storageBucket: 'a4c-shop-ae65c.appspot.com',
  );
}
